from PyQt5 import QtCore, QtGui, QtWidgets
from conectabanco import ConectaBanco
import serial                                           #Obs IMPORTANTE, sempre use ".self" no começo nos parametros das funcoes ->(self), e no começo de toda Variavel self.nomeVariavel dentro das Classes 


class Ui_janelaConsultarMorador(object):
    def setupUi(self, janelaConsultarMorador):
        janelaConsultarMorador.setObjectName("janelaConsultarMorador")
        janelaConsultarMorador.resize(725, 610)
        janelaConsultarMorador.setMinimumSize(QtCore.QSize(725, 610))
        janelaConsultarMorador.setMaximumSize(QtCore.QSize(725, 610))
        janelaConsultarMorador.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(janelaConsultarMorador)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxConsultarMoradores = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxConsultarMoradores.setEnabled(True)
        self.comboBoxConsultarMoradores.setGeometry(QtCore.QRect(30, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBoxConsultarMoradores.setFont(font)
        self.comboBoxConsultarMoradores.setObjectName("comboBoxConsultarMoradores")
        self.comboBoxConsultarMoradores.addItem("")
        self.comboBoxConsultarMoradores.addItem("")
        self.comboBoxConsultarMoradores.addItem("")
        self.inputConsultarMoradores = QtWidgets.QTextEdit(self.centralwidget)
        self.inputConsultarMoradores.setGeometry(QtCore.QRect(190, 110, 511, 31))
        self.inputConsultarMoradores.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputConsultarMoradores.setToolTipDuration(-1)
        self.inputConsultarMoradores.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.inputConsultarMoradores.setTabChangesFocus(True)
        self.inputConsultarMoradores.setPlaceholderText("")
        self.inputConsultarMoradores.setObjectName("inputConsultarMoradores")
        self.lblCampoPesquisa = QtWidgets.QLabel(self.centralwidget)
        self.lblCampoPesquisa.setGeometry(QtCore.QRect(30, 80, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblCampoPesquisa.setFont(font)
        self.lblCampoPesquisa.setObjectName("lblCampoPesquisa")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 50, 671, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lblTituloConsultarMoradores = QtWidgets.QLabel(self.centralwidget)
        self.lblTituloConsultarMoradores.setGeometry(QtCore.QRect(30, 20, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblTituloConsultarMoradores.setFont(font)
        self.lblTituloConsultarMoradores.setObjectName("lblTituloConsultarMoradores")
        self.tblConsultarMorador = QtWidgets.QTableWidget(self.centralwidget)
        self.tblConsultarMorador.setGeometry(QtCore.QRect(30, 160, 671, 351))
        self.tblConsultarMorador.setObjectName("tblConsultarMorador")
        self.tblConsultarMorador.setColumnCount(6)
        self.tblConsultarMorador.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Nome ")
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tblConsultarMorador.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultarMorador.setHorizontalHeaderItem(5, item)
        self.tblConsultarMorador.horizontalHeader().setVisible(True)
        self.tblConsultarMorador.horizontalHeader().setDefaultSectionSize(200)
        self.tblConsultarMorador.horizontalHeader().setStretchLastSection(True)
        self.tblConsultarMorador.verticalHeader().setVisible(False)
        self.tblConsultarMorador.verticalHeader().setSortIndicatorShown(False)
        self.tblConsultarMorador.verticalHeader().setStretchLastSection(True)
        self.btnAlterar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlterar.setGeometry(QtCore.QRect(570, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnAlterar.setFont(font)
        self.btnAlterar.setAutoDefault(False)
        self.btnAlterar.setObjectName("btnAlterar")
        self.btnBuscarMoradores = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscarMoradores.setGeometry(QtCore.QRect(600, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnBuscarMoradores.setFont(font)
        self.btnBuscarMoradores.setObjectName("btnBuscarMoradores")
        self.btnLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpar.setGeometry(QtCore.QRect(430, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnLimpar.setFont(font)
        self.btnLimpar.setObjectName("btnLimpar")
        janelaConsultarMorador.setCentralWidget(self.centralwidget)

        self.retranslateUi(janelaConsultarMorador)
        self.btnLimpar.clicked.connect(self.tblConsultarMorador.clearContents)
        self.btnLimpar.clicked.connect(self.inputConsultarMoradores.clear)
        QtCore.QMetaObject.connectSlotsByName(janelaConsultarMorador)
        janelaConsultarMorador.setTabOrder(self.comboBoxConsultarMoradores, self.inputConsultarMoradores)
        janelaConsultarMorador.setTabOrder(self.inputConsultarMoradores, self.btnBuscarMoradores)
        janelaConsultarMorador.setTabOrder(self.btnBuscarMoradores, self.tblConsultarMorador)
        janelaConsultarMorador.setTabOrder(self.tblConsultarMorador, self.btnLimpar)
        janelaConsultarMorador.setTabOrder(self.btnLimpar, self.btnAlterar)

    def retranslateUi(self, janelaConsultarMorador):
        _translate = QtCore.QCoreApplication.translate
        janelaConsultarMorador.setWindowTitle(_translate("janelaConsultarMorador", "Prime Condo"))
        self.comboBoxConsultarMoradores.setItemText(0, _translate("janelaConsultarMorador", "Nome "))
        self.comboBoxConsultarMoradores.setItemText(1, _translate("janelaConsultarMorador", "CPF (só números)"))
        self.comboBoxConsultarMoradores.setItemText(2, _translate("janelaConsultarMorador", "Veículo (placa)"))
        self.inputConsultarMoradores.setHtml(_translate("janelaConsultarMorador", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lblCampoPesquisa.setText(_translate("janelaConsultarMorador", "Selecione o campo que deseja pesquisar"))
        self.lblTituloConsultarMoradores.setText(_translate("janelaConsultarMorador", "Consultar Moradores"))
        item = self.tblConsultarMorador.verticalHeaderItem(0)
        item.setText(_translate("janelaConsultarMorador", "1"))
        item = self.tblConsultarMorador.verticalHeaderItem(1)
        item.setText(_translate("janelaConsultarMorador", "2"))
        item = self.tblConsultarMorador.verticalHeaderItem(2)
        item.setText(_translate("janelaConsultarMorador", "3"))
        item = self.tblConsultarMorador.verticalHeaderItem(3)
        item.setText(_translate("janelaConsultarMorador", "4"))
        item = self.tblConsultarMorador.verticalHeaderItem(4)
        item.setText(_translate("janelaConsultarMorador", "5"))
        item = self.tblConsultarMorador.verticalHeaderItem(5)
        item.setText(_translate("janelaConsultarMorador", "6"))
        item = self.tblConsultarMorador.verticalHeaderItem(6)
        item.setText(_translate("janelaConsultarMorador", "7"))
        item = self.tblConsultarMorador.verticalHeaderItem(7)
        item.setText(_translate("janelaConsultarMorador", "8"))
        item = self.tblConsultarMorador.verticalHeaderItem(8)
        item.setText(_translate("janelaConsultarMorador", "9"))
        item = self.tblConsultarMorador.verticalHeaderItem(9)
        item.setText(_translate("janelaConsultarMorador", "10"))
        item = self.tblConsultarMorador.verticalHeaderItem(10)
        item.setText(_translate("janelaConsultarMorador", "11"))
        item = self.tblConsultarMorador.verticalHeaderItem(11)
        item.setText(_translate("janelaConsultarMorador", "12"))
        item = self.tblConsultarMorador.horizontalHeaderItem(1)
        item.setText(_translate("janelaConsultarMorador", "Bloco"))
        item = self.tblConsultarMorador.horizontalHeaderItem(2)
        item.setText(_translate("janelaConsultarMorador", "Nº Apt."))
        item = self.tblConsultarMorador.horizontalHeaderItem(3)
        item.setText(_translate("janelaConsultarMorador", "Nº da Vaga"))
        item = self.tblConsultarMorador.horizontalHeaderItem(4)
        item.setText(_translate("janelaConsultarMorador", "Tipo"))
        item = self.tblConsultarMorador.horizontalHeaderItem(5)
        item.setText(_translate("janelaConsultarMorador", "Status"))
        self.btnAlterar.setText(_translate("janelaConsultarMorador", "ALTERAR"))
        self.btnBuscarMoradores.setText(_translate("janelaConsultarMorador", "Buscar"))
        self.btnLimpar.setText(_translate("janelaConsultarMorador", "LIMPAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janelaConsultarMorador = QtWidgets.QMainWindow()
    ui = Ui_janelaConsultarMorador()
    ui.setupUi(janelaConsultarMorador)
    janelaConsultarMorador.show()
    sys.exit(app.exec_())
