
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaLogin(object):
    def setupUi(self, janelaLogin):
        janelaLogin.setObjectName("janelaLogin")
        janelaLogin.resize(482, 430)
        janelaLogin.setMinimumSize(QtCore.QSize(482, 430))
        janelaLogin.setMaximumSize(QtCore.QSize(482, 430))
        self.lblLogin = QtWidgets.QLabel(janelaLogin)
        self.lblLogin.setGeometry(QtCore.QRect(100, 130, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogin.setFont(font)
        self.lblLogin.setObjectName("lblLogin")
        self.lblSenha = QtWidgets.QLabel(janelaLogin)
        self.lblSenha.setGeometry(QtCore.QRect(100, 210, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblSenha.setFont(font)
        self.lblSenha.setObjectName("lblSenha")
        self.btnEntrar = QtWidgets.QPushButton(janelaLogin)
        self.btnEntrar.setGeometry(QtCore.QRect(200, 260, 93, 28))
        self.btnEntrar.setAutoDefault(False)
        self.btnEntrar.setObjectName("btnEntrar")
        self.inputLogin = QtWidgets.QLineEdit(janelaLogin)
        self.inputLogin.setGeometry(QtCore.QRect(160, 121, 191, 26))
        self.inputLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputLogin.setObjectName("inputLogin")
        self.inputSenha = QtWidgets.QLineEdit(janelaLogin)
        self.inputSenha.setGeometry(QtCore.QRect(160, 200, 191, 26))
        self.inputSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputSenha.setObjectName("inputSenha")
        self.lblTituloPrimeCondo = QtWidgets.QLabel(janelaLogin)
        self.lblTituloPrimeCondo.setGeometry(QtCore.QRect(170, 50, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTituloPrimeCondo.setFont(font)
        self.lblTituloPrimeCondo.setObjectName("lblTituloPrimeCondo")
        self.lblEsqueceuSenha = QtWidgets.QLabel(janelaLogin)
        self.lblEsqueceuSenha.setGeometry(QtCore.QRect(40, 370, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblEsqueceuSenha.setFont(font)
        self.lblEsqueceuSenha.setObjectName("lblEsqueceuSenha")
        self.lblLogin.setBuddy(self.inputLogin)
        self.lblSenha.setBuddy(self.inputSenha)

        self.retranslateUi(janelaLogin)
        QtCore.QMetaObject.connectSlotsByName(janelaLogin)
        janelaLogin.setTabOrder(self.inputLogin, self.inputSenha)
        janelaLogin.setTabOrder(self.inputSenha, self.btnEntrar)

    def retranslateUi(self, janelaLogin):
        _translate = QtCore.QCoreApplication.translate
        janelaLogin.setWindowTitle(_translate("janelaLogin", "Prime Condo"))
        self.lblLogin.setText(_translate("janelaLogin", "&LOGIN"))
        self.lblSenha.setText(_translate("janelaLogin", "&SENHA"))
        self.btnEntrar.setText(_translate("janelaLogin", "ENTRAR"))
        self.lblTituloPrimeCondo.setText(_translate("janelaLogin", "PRIME CONDO"))
        self.lblEsqueceuSenha.setText(_translate("janelaLogin", "Esqueceu a Senha?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janelaLogin = QtWidgets.janelaLogin()
    ui = Ui_janelaLogin()
    ui.setupUi(janelaLogin)
    janelaLogin.show()
    sys.exit(app.exec_())
