from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaLogin(object):
    def setupUi(self, janelaLogin):
        janelaLogin.setObjectName("janelaLogin")
        janelaLogin.resize(482, 430)
        janelaLogin.setMinimumSize(QtCore.QSize(482, 430))
        janelaLogin.setMaximumSize(QtCore.QSize(482, 430))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        janelaLogin.setWindowIcon(icon)
        janelaLogin.setStyleSheet("")
        self.lblLogin = QtWidgets.QLabel(janelaLogin)
        self.lblLogin.setGeometry(QtCore.QRect(100, 165, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogin.setFont(font)
        self.lblLogin.setStyleSheet("image: url(:/janelaLogin/icons/user.png);")
        self.lblLogin.setObjectName("lblLogin")
        self.lblSenha = QtWidgets.QLabel(janelaLogin)
        self.lblSenha.setGeometry(QtCore.QRect(100, 245, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblSenha.setFont(font)
        self.lblSenha.setStyleSheet("image: url(:/janelaLogin/icons/password.png);")
        self.lblSenha.setObjectName("lblSenha")
        self.btnEntrar = QtWidgets.QPushButton(janelaLogin)
        self.btnEntrar.setGeometry(QtCore.QRect(200, 310, 93, 28))
        self.btnEntrar.setAutoDefault(False)
        self.btnEntrar.setObjectName("btnEntrar")
        self.inputLogin = QtWidgets.QLineEdit(janelaLogin)
        self.inputLogin.setGeometry(QtCore.QRect(160, 171, 191, 26))
        self.inputLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputLogin.setMaxLength(20)
        self.inputLogin.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.inputLogin.setObjectName("inputLogin")
        self.inputSenha = QtWidgets.QLineEdit(janelaLogin)
        self.inputSenha.setGeometry(QtCore.QRect(160, 250, 191, 26))
        self.inputSenha.setMaxLength(20)
        self.inputSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputSenha.setObjectName("inputSenha")
        self.lblTituloPrimeCondo = QtWidgets.QLabel(janelaLogin)
        self.lblTituloPrimeCondo.setGeometry(QtCore.QRect(180, 20, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTituloPrimeCondo.setFont(font)
        self.lblTituloPrimeCondo.setStyleSheet("image: url(:/janelaLogin/icons/imgLoginCenter.png);")
        self.lblTituloPrimeCondo.setObjectName("lblTituloPrimeCondo")
        self.lblEsqueceuSenha = QtWidgets.QLabel(janelaLogin)
        self.lblEsqueceuSenha.setGeometry(QtCore.QRect(40, 370, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblEsqueceuSenha.setFont(font)
        self.lblEsqueceuSenha.setObjectName("lblEsqueceuSenha")
        self.lblLogin.setBuddy(self.inputLogin)
        self.lblSenha.setBuddy(self.inputSenha)

        self.retranslateUi(janelaLogin)
        QtCore.QMetaObject.connectSlotsByName(janelaLogin)
        janelaLogin.setTabOrder(self.inputLogin, self.inputSenha)
        janelaLogin.setTabOrder(self.inputSenha, self.btnEntrar)

    def retranslateUi(self, janelaLogin):
        _translate = QtCore.QCoreApplication.translate
        janelaLogin.setWindowTitle(_translate("janelaLogin", "Prime Condo"))
        self.lblLogin.setText(_translate("janelaLogin", "<html><head/><body><p><br/></p></body></html>"))
        self.lblSenha.setText(_translate("janelaLogin", "<html><head/><body><p><br/></p></body></html>"))
        self.btnEntrar.setText(_translate("janelaLogin", "ENTRAR"))
        self.inputLogin.setPlaceholderText(_translate("janelaLogin", "Digite seu Nome de Usuário"))
        self.inputSenha.setPlaceholderText(_translate("janelaLogin", "Digite sua Senha"))
        self.lblTituloPrimeCondo.setText(_translate("janelaLogin", "<html><head/><body><p><br/></p></body></html>"))
        self.lblEsqueceuSenha.setText(_translate("janelaLogin", "Dica de Senha Login: admin, Senha:admin"))
import janelaLogin


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janelaLogin = QtWidgets.QDialog()
    ui = Ui_janelaLogin()
    ui.setupUi(janelaLogin)
    janelaLogin.show()
    sys.exit(app.exec_())
