# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName("Principal")
        Principal.resize(965, 708)
        Principal.setMinimumSize(QtCore.QSize(965, 708))
        Principal.setMaximumSize(QtCore.QSize(965, 708))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/img_center.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Principal.setWindowIcon(icon)
        Principal.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Principal)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 971, 671))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 50, 621, 481))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../wamp64/www/primecondo/assets/img/imgLoginCenter.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        Principal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuCadastro_de_Visitantes = QtWidgets.QMenu(self.menubar)
        self.menuCadastro_de_Visitantes.setObjectName("menuCadastro_de_Visitantes")
        Principal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Principal)
        self.statusbar.setObjectName("statusbar")
        Principal.setStatusBar(self.statusbar)
        self.btnActCadastro = QtWidgets.QAction(Principal)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/identity_card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActCadastro.setIcon(icon1)
        self.btnActCadastro.setObjectName("btnActCadastro")
        self.btnActAtualizarMoradores = QtWidgets.QAction(Principal)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/refresh-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActAtualizarMoradores.setIcon(icon2)
        self.btnActAtualizarMoradores.setObjectName("btnActAtualizarMoradores")
        self.btnActAtivarDesativarMoradores = QtWidgets.QAction(Principal)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/delete-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActAtivarDesativarMoradores.setIcon(icon3)
        self.btnActAtivarDesativarMoradores.setObjectName("btnActAtivarDesativarMoradores")
        self.btnActNovoVisitante = QtWidgets.QAction(Principal)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/add-visitors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActNovoVisitante.setIcon(icon4)
        self.btnActNovoVisitante.setObjectName("btnActNovoVisitante")
        self.btnActSair = QtWidgets.QAction(Principal)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/logout-account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActSair.setIcon(icon5)
        self.btnActSair.setObjectName("btnActSair")
        self.btnActConsultarVisitantes = QtWidgets.QAction(Principal)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/cons-visitors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActConsultarVisitantes.setIcon(icon6)
        self.btnActConsultarVisitantes.setObjectName("btnActConsultarVisitantes")
        self.btnActAtivarDesativarVisitantes = QtWidgets.QAction(Principal)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/upd-visitors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActAtivarDesativarVisitantes.setIcon(icon7)
        self.btnActAtivarDesativarVisitantes.setObjectName("btnActAtivarDesativarVisitantes")
        self.btnActCadastrarMoradores = QtWidgets.QAction(Principal)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActCadastrarMoradores.setIcon(icon8)
        self.btnActCadastrarMoradores.setObjectName("btnActCadastrarMoradores")
        self.btnActConsultarMoradores = QtWidgets.QAction(Principal)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/janelaPrincipal/icons/cancel-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnActConsultarMoradores.setIcon(icon9)
        self.btnActConsultarMoradores.setObjectName("btnActConsultarMoradores")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.btnActCadastro)
        self.menuFile.addAction(self.btnActSair)
        self.menuEdit.addAction(self.btnActCadastrarMoradores)
        self.menuEdit.addAction(self.btnActConsultarMoradores)
        self.menuEdit.addAction(self.btnActAtualizarMoradores)
        self.menuEdit.addAction(self.btnActAtivarDesativarMoradores)
        self.menuCadastro_de_Visitantes.addAction(self.btnActNovoVisitante)
        self.menuCadastro_de_Visitantes.addAction(self.btnActConsultarVisitantes)
        self.menuCadastro_de_Visitantes.addAction(self.btnActAtivarDesativarVisitantes)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuCadastro_de_Visitantes.menuAction())

        self.retranslateUi(Principal)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        _translate = QtCore.QCoreApplication.translate
        Principal.setWindowTitle(_translate("Principal", "Prime Condo"))
        self.label.setText(_translate("Principal", "<html><head/><body><p><br/></p></body></html>"))
        self.menuFile.setTitle(_translate("Principal", "CONTA"))
        self.menuEdit.setTitle(_translate("Principal", "MORADORES"))
        self.menuCadastro_de_Visitantes.setTitle(_translate("Principal", "VISITANTES"))
        self.btnActCadastro.setText(_translate("Principal", "Cadastro"))
        self.btnActAtualizarMoradores.setText(_translate("Principal", "Atualizar Moradores"))
        self.btnActAtivarDesativarMoradores.setText(_translate("Principal", "Desativar / Ativar - Moradores"))
        self.btnActAtivarDesativarMoradores.setToolTip(_translate("Principal", "Ativar / Desativar - Moradores"))
        self.btnActNovoVisitante.setText(_translate("Principal", "Novo Visitante"))
        self.btnActSair.setText(_translate("Principal", "Sair"))
        self.btnActConsultarVisitantes.setText(_translate("Principal", "Consultar Visitantes"))
        self.btnActAtivarDesativarVisitantes.setText(_translate("Principal", "Desativar / Ativar - Visitantes"))
        self.btnActCadastrarMoradores.setText(_translate("Principal", "Cadastrar Moradores"))
        self.btnActCadastrarMoradores.setToolTip(_translate("Principal", "Cadastrar Moradores"))
        self.btnActConsultarMoradores.setText(_translate("Principal", "Consultar Moradores"))
        self.btnActConsultarMoradores.setToolTip(_translate("Principal", "Consultar Moradores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_Principal()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())
